### ISSUE TITLE
Fix documentation for variables declared in inherited abstract contracts

### ISSUE THREAD

**Issue by Mc01** [dl-solarity/hardhat-markup#10]
Bug request:

Correctly described variable declared in abstract contract, that child contract inherits is not showed in documentation generated for child.

Code affected:

```
abstract contract A {
  /// @dev Description
  uint256 public varA;
}

contract B is A {}
```

Expected result: Documentation correctly includes "Description" in contract "B".

**Comment by Arvolear** [comment]
The new parser will handle the inheritance a bit differently, however, we will keep the `abstract contract` inheritance in mind. Thanks
