### ISSUE TITLE
✨ Add some examples of generated files

### ISSUE THREAD

**Issue by Velnbur** [dl-solarity/hardhat-markup#16]
This could be done by adding `examples/` directory that includes a small example projects that contain generated from them documentation files.

As example could be many **Rust** projects:

- [Yew](https://github.com/yewstack/yew/tree/master/examples/counter)
- [Bevy](https://github.com/bevyengine/bevy/tree/main/examples)
- etc..

**Comment by Arvolear** [comment]
Done!
