### ISSUE TITLE
Space between multiple lines

### ISSUE THREAD

**Issue by Mc01** [dl-solarity/hardhat-markup#7]
Feature idea:

If in the code there are multiple dev comments:
```
/// @dev Validation: Only contract owner can perform this function.
/// @dev Validation: This function can be performed only once.
```
Rendered markup doesn't add space between those lines.

Current result: Validation: `Only contract owner can perform this function.Validation: This function can be performed only once.`
Expected result: Validation: `Only contract owner can perform this function. Validation: This function can be performed only once.`

**Comment by Arvolear** [comment]
Hey, thanks for the report. We are working on a new version of the parser, so this issue should be solved when it is released.
