### ISSUE TITLE
Support for @custom markup

### ISSUE THREAD

**Issue by Mc01** [dl-solarity/hardhat-markup#8]
Feature idea:

Would be cool to support `@custom:...` from NatSpec documentation: https://docs.soliditylang.org/en/v0.8.17/natspec-format.html#tags

Potential code usage:
```
/// @custom:validation Only contract owner can perform this function
/// @custom:validation This function can be performed only once
```

Potential result: Additional section below description or parameters.

**Comment by Arvolear** [comment]
Thanks, will consider that after the work on a new parser is done.
