### ISSUE TITLE
Optional struct support

### ISSUE THREAD

**Issue by Mc01** [dl-solarity/hardhat-markup#9]
Feature idea: 

Would be cool to receive optional struct support.

Potential code usage:
```
/// @dev Example struct description
/// @param structMember Example member description
struct ExampleStruct {
  uint256 structMember;
}
```

Potential results: Structs added as an optional to render additional section with suggested markup.

**Comment by Arvolear** [comment]
The new parser will also be able to handle that. Thanks.
